### ISSUE TITLE
add environments

### ISSUE THREAD

**Issue by torfeld6** [torfeld6/kudu#7]
kudu push [file_id] [source]

```yaml
environments:
  workbench:
    file_id: 
    path: .
    on:
      branch: master
```
